"use client";
import { useState, type FormEvent, type ReactNode } from "react";
import { CalendarDays, LoaderCircle } from "lucide-react";
import Link from "next/link";
import { createDiningPlan, type DiningPlanRequest, type DiningPlanResponse } from "@/lib/api";
import { MealCalendar } from "./meal-calendar";
export function DiningPlanner() {
  const [plan, setPlan] = useState<DiningPlanResponse | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setLoading(true); setError(""); const data = new FormData(event.currentTarget);
    const input = { diningPlan: String(data.get("diningPlan")), studentStatus: String(data.get("studentStatus")), diningBalanceCents: Math.round(Number(data.get("diningBalance")) * 100), hokiePassportBalanceCents: Math.round(Number(data.get("hokiePassportBalance")) * 100), weeksRemaining: Number(data.get("weeksRemaining")), preferences: String(data.get("preferences")), allowHokiePassport: data.get("allowHokiePassport") === "on" } as DiningPlanRequest;
    try { setPlan(await createDiningPlan(input)); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not create the meal plan."); } finally { setLoading(false); }
  }
  return <><form onSubmit={submit} className="dining-form mt-10 rounded-2xl border bg-card p-6 shadow-sm sm:p-8"><div className="dining-fields grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><Field label="Dining plan"><select name="diningPlan" defaultValue="Unlimited">{["Unlimited","Unlimited Plus","Maroon","Maroon Plus","Orange","Orange Plus","Dining Dollars only"].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Student status"><select name="studentStatus"><option>First-year, on campus</option><option>Upper-year, on campus</option><option>Off campus</option></select></Field><Field label="Dining balance ($)"><input name="diningBalance" type="number" min="0" step="0.01" defaultValue="225" required /></Field><Field label="Hokie Passport balance ($)"><input name="hokiePassportBalance" type="number" min="0" step="0.01" defaultValue="0" required /></Field><Field label="Weeks remaining"><input name="weeksRemaining" type="number" min="1" max="36" defaultValue="15" required /></Field></div><Field label="Preferences, dietary needs, and schedule" wide><textarea name="preferences" minLength={3} maxLength={2000} required placeholder="Vegetarian, peanut allergy, early classes M/W/F, quick breakfasts…" /></Field>
    <label className="dining-fallback mt-4 flex items-center gap-3 text-sm"><input className="size-4" type="checkbox" name="allowHokiePassport" /> Allow Hokie Passport funds as a fallback</label><div className="dining-actions mt-6 flex flex-wrap items-center gap-4"><button disabled={loading} className="dining-submit inline-flex items-center gap-2 rounded-lg bg-primary px-5 py-3 font-semibold text-white disabled:opacity-60">{loading ? <LoaderCircle className="size-4 animate-spin"/> : <CalendarDays className="size-4"/>}{loading ? "Building your week…" : "Create meal calendar"}</button><Link href="/demo" className="dining-demo-link text-sm font-semibold text-primary underline">View instant demo</Link></div>{error && <p role="alert" className="mt-5 rounded-lg bg-red-50 p-3 text-sm font-medium text-red-800">{error}</p>}</form>{plan && <MealCalendar plan={plan} />}</>;
}
function Field({ label, children, wide = false }: { label: string; children: ReactNode; wide?: boolean }) { return <label className={`dining-field flex flex-col gap-2 text-xs font-semibold uppercase tracking-wider ${wide ? "mt-5" : ""}`}><span>{label}</span>{children}</label>; }
