import type { DiningPlanResponse } from "@/lib/api";
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });
const labels = { swipe: "Swipe", meal_exchange: "Meal exchange", dining_balance: "Dining balance", hokie_passport: "Hokie Passport", other: "Other" };
export function MealCalendar({ plan, sample = false }: { plan: DiningPlanResponse; sample?: boolean }) {
  const providerLabel = plan.source === "openrouter" ? "OpenRouter" : "VT ARC";
  return <section className="mt-10" aria-labelledby="calendar-title"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow">{sample ? "Synthetic demo" : `Your ${providerLabel} plan`}</p><h2 id="calendar-title" className="font-sans font-bold text-3xl">Weekly meal calendar</h2></div><a className="text-sm font-semibold text-primary underline" href={plan.hoursUrl} target="_blank" rel="noreferrer">Check live dining hours ↗</a></div>
    <p className="mt-4 max-w-3xl text-sm leading-6 text-muted-foreground">{plan.strategy}</p>
    <div className="calendar-grid mt-7">{plan.days.map((entry) => <article key={entry.day} className="min-w-52 overflow-hidden rounded-xl border bg-card"><div className="bg-primary px-4 py-3 text-white"><h3 className="font-sans font-bold text-lg">{entry.day}</h3></div>{entry.meals.map((meal) => <div key={meal.label} className="border-b p-4 last:border-0"><div className="flex items-center justify-between gap-2"><span className="text-[.68rem] font-bold uppercase tracking-widest text-primary">{meal.label}</span><span className="rounded-full bg-muted px-2 py-0.5 text-[.65rem]">{labels[meal.payment]}</span></div><strong className="mt-2 block text-sm">{meal.venue}</strong><p className="mt-1 text-xs leading-5 text-muted-foreground">{meal.suggestion}</p>{meal.estimatedCostCents > 0 && <p className="mt-2 text-xs font-semibold">Est. {money.format(meal.estimatedCostCents / 100)}</p>}</div>)}</article>)}</div>
    <div className="mt-7 grid gap-4 sm:grid-cols-3"><Stat label="Estimated weekly restricted spend" value={money.format(plan.weeklyDiningSpendCents / 100)} /><Stat label="Projected remaining-term spend" value={money.format(plan.projectedDiningSpendCents / 100)} /><Stat label="Projected dining balance" value={money.format(plan.remainingDiningBalanceCents / 100)} /></div>
    {(plan.warnings.length > 0 || plan.assumptions.length > 0) && <div className="mt-6 grid gap-5 rounded-xl bg-muted p-5 md:grid-cols-2"><Notes title="Assumptions" items={plan.assumptions}/><Notes title="Important notes" items={plan.warnings}/></div>}</section>;
}
function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-sans font-bold text-2xl">{value}</p></div>; }
function Notes({ title, items }: { title: string; items: string[] }) { return <div><h3 className="text-sm font-semibold">{title}</h3><ul className="mt-2 list-disc space-y-1 pl-5 text-xs leading-5 text-muted-foreground">{items.map((item) => <li key={item}>{item}</li>)}</ul></div>; }
